nsqd:
  image: nsqio/nsq
  command: /nsqd
  expose:
    - 4150
    - 4151
monitor:
  image: quay.io/opsee/bastion
  command: /monitor -level debug
  links:
    - nsqd
  ports:
    - 4000:4000
checker:
  image: quay.io/opsee/bastion
  command: /checker -metadata /metadata.json -level debug
  volumes:
    - metadata.json:/metadata.json
  expose:
    - 4000
  links:
    - nsqd
discovery:
  image: quay.io/opsee/bastion
  command: /discovery -metadata /metadata.json -level debug
  volumes:
    - metadata.json:/metadata.json
  environment:
    AWS_ACCESS_KEY_ID:
    AWS_DEFAULT_REGION:
    AWS_SECRET_ACCESS_KEY:
  links:
    - nsqd
connector:
  image: quay.io/opsee/bastion
  command: /connector -metadata /metadata.json -level debug
  volumes:
    - metadata.json:/metadata.json
  external_links:
    - vagabond_bartnet_1:bartnet-api
  links:
    - nsqd
