nsqd:
  image: nsqio/nsq
  command: /nsqd
  ports:
    - 4150:4150
    - 4151:4151
monitor:
  image: quay.io/opsee/bastion
  command: /monitor -level debug
  links:
    - nsqd
  ports:
    - 4000:4000
checker:
  image: quay.io/opsee/bastion
  command: /checker -metadata /metadata.json -level debug
  volumes:
    - metadata.json:/metadata.json
  ports:
    - 5000:4000
  environment:
    AWS_ACCESS_KEY_ID:
    AWS_DEFAULT_REGION:
    AWS_SECRET_ACCESS_KEY:
  links:
    - nsqd
discovery:
  image: quay.io/opsee/bastion
  command: /discovery -metadata /metadata.json -level debug
  volumes:
    - metadata.json:/metadata.json
  environment:
    AWS_ACCESS_KEY_ID:
    AWS_DEFAULT_REGION:
    AWS_SECRET_ACCESS_KEY:
  links:
    - nsqd
